### ISSUE TITLE
What is the storage mechanism for the PGSQL?

### ISSUE THREAD

**Issue by wayne-o** [cappalyst/cappalyst-pulumi#2]
Hi 

I am just having a look at the code here and I think if this works it would be a really good help in moving some of my code away from shell scripts and into Pulumi - One quick q though - what is the storage mechanism for PGSQL? I don't see any volumes or storage classes?

**Comment by sylv3r** [comment]
Hi @wayne-o 

Thanks for your interest on this project. Please keep in mind this is an early stage project in the pulumi typescript ecosystem.

The `PostgreSQL` module is actually a wrapper around the Helm Chart bitnami for postgreSQL (which seems to have been renamed since I made the wrapper..) here https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha so the chart handles storage and everything.

I am not satisfied with the way it is right now and should probably be rewrote from  scratch (maybe with the new helm chart that would solve a few problems I had with it).

I would not recommend to use it as-is right now, and certainly not in production, but you can definitely uses it as an example on how to migrate to pulumi for your needs.

I intend to write docs as soon as I find the time to and push this project further.
